/**
 * Auth design tokens — product palette from design handoff.
 */
export const AUTH_TOKENS = {
  primary: '#006DEC',
  primaryHover: '#0059c4',
  text: '#1c2842',
  muted: '#62748e',
  border: '#e2e8f0',
  surface: '#ffffff',
  promoBg: '#F1F6FD',
  linkPill: '#e8f1fe',
  error: '#dc2626',
  success: '#16a34a',
  font: '"Plus Jakarta Sans", system-ui, sans-serif',
} as const;

export const AUTH_COPY = {
  signIn: {
    title: 'Welcome back 👋',
    subtitle: 'Sign in to your account to continue',
    emailLabel: 'Email address',
    emailPlaceholder: 'Enter your email',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter your password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    submit: 'Sign in',
    orContinue: 'or continue with',
    google: 'Continue with Google',
    microsoft: 'Continue with Microsoft',
    noAccount: "Don't have an account?",
    signUpLink: 'Sign up',
    verifyNeeded: 'Please verify your email before signing in.',
    resendVerification: 'Resend verification email',
    verificationResent: 'Verification email sent. Check your inbox.',
  },
  signUp: {
    title: 'Create your account',
    subtitle: 'Start your journey with Samtal and experience smarter collaboration.',
    formTitle: 'Sign up',
    firstNameLabel: 'First name',
    firstNamePlaceholder: 'Enter your first name',
    lastNameLabel: 'Last name',
    lastNamePlaceholder: 'Enter your last name',
    emailLabel: 'Work email',
    emailPlaceholder: 'Enter your work email',
    companyLabel: 'Company name',
    companyPlaceholder: 'Enter your company name',
    teamSizeLabel: 'Team size',
    teamSizePlaceholder: 'Select team size',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Create a password',
    passwordHint: 'Must be at least 8 characters with a number and a special character.',
    confirmLabel: 'Confirm password',
    confirmPlaceholder: 'Confirm your password',
    termsPrefix: 'I agree to the ',
    termsOfService: 'Terms of Service',
    termsAnd: ' and ',
    privacyPolicy: 'Privacy Policy',
    submit: 'Create Account',
    orContinue: 'or sign up with',
    google: 'Sign up with Google',
    microsoft: 'Sign up with Microsoft',
    hasAccount: 'Already have an account?',
    signInLink: 'Sign in',
    verifyTitle: 'Check your email',
    verifyBodyPrefix: 'We sent a Samhal verification link to',
    verifyBodySuffix:
      '. Open the link to activate your organization account, then sign in with the password you created. The link expires in 1 hour.',
    verifyResend: 'Resend verification email',
    verifyResent: 'Verification email sent. Check your inbox.',
    verifyGoSignIn: 'Go to sign in',
    feature1Title: 'All-in-one platform',
    feature1Body: 'Manage meetings, recordings, tasks, and teams in one place.',
    feature2Title: 'Secure & reliable',
    feature2Body: 'Enterprise-grade security to keep your data safe and compliant.',
    feature3Title: 'Insights that matter',
    feature3Body: 'Powerful reports and analytics to help you make better decisions.',
  },
  forgot: {
    title: 'Forgot Password?',
    subtitle:
      "No worries! Enter your email address and we'll send you a link to reset your password.",
    emailLabel: 'Email address',
    emailPlaceholder: 'Enter your email address',
    submit: 'Send Reset Link',
    back: 'Back to Sign In',
    tip1Title: 'Secure & safe',
    tip1Body: 'We use industry-standard security to protect your account.',
    tip2Title: 'Quick recovery',
    tip2Body: 'Reset your password and get back to work in minutes.',
    tip3Title: 'Need help?',
    tip3Body: 'Contact our support team if you need any assistance.',
    sentTitle: 'Check your inbox',
    sentBodyPrefix: 'If an account exists for',
    sentBodySuffix: ', a password reset link has been sent. It expires in 30 minutes.',
  },
  reset: {
    title: 'Choose a new password',
    subtitle:
      'Your password must be at least 10 characters with upper & lowercase letters and a number.',
    passwordLabel: 'New password',
    passwordPlaceholder: 'Enter new password',
    confirmLabel: 'Confirm password',
    confirmPlaceholder: 'Confirm new password',
    submit: 'Set new password',
  },
  promo: {
    workTitle: 'Work smarter',
    workBody: 'Manage your meetings, tasks, and team in one place.',
    organizeTitle: 'Stay organized',
    organizeBody: 'Calendar, recordings, and reports at your fingertips.',
    collabTitle: 'Collaborate seamlessly',
    collabBody: 'Connect with your team and achieve more together.',
  },
  footer: {
    copyright: '© 2025 Samtal. All rights reserved.',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
  },
  oauthUnavailable: 'Social sign-in is not available yet.',
  teamSizes: ['1–10', '11–50', '51–200', '201–1000', '1000+'] as const,
} as const;
